### ISSUE TITLE
TooManyRequestsException on thread creation

### ISSUE THREAD

**Issue by TheToddLuci0** [knavesec/CredMaster#54]
```
[2023-05-24 17:57:11.973] Execution started at: 2023-05-24 17:57:11.973820
[2023-05-24 17:57:11.975] Creating 15 API Gateways for https://login.microsoftonline.com
[2023-05-24 17:57:13.112] Created API - Region: us-east-2 ID: (xxxxxxx) - https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/fireprox/ => https://login.microsoftonline.com
[2023-05-24 17:57:19.082] Created API - Region: us-east-1 ID: (xxxxxxxxx) - https://xxxxxxxxxxx.execute-api.us-east-1.amazonaws.com/fireprox/ => https://login.microsoftonline.com
[2023-05-24 17:57:23.063] Created API - Region: us-west-1 ID: (xxxxxxxxx) - https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/fireprox/ => https://login.microsoftonline.com
[2023-05-24 17:57:28.840] Created API - Region: us-west-2 ID: (xxxxxxxxxx) - https://xxxxxxxxx.execute-api.us-east-1.amazonaws.com/fireprox/ => https://login.microsoftonline.com
Traceback (most recent call last):
  File "/home/kali/git/CredMaster/credmaster.py", line 706, in <module>
    CredMaster(args, pluginargs)
  File "/home/kali/git/CredMaster/credmaster.py", line 54, in __init__
    self.Execute(args)
  File "/home/kali/git/CredMaster/credmaster.py", line 236, in Execute
    self.load_apis(url, region = self.region)
  File "/home/kali/git/CredMaster/credmaster.py", line 359, in load_apis
    self.apis.append(self.create_api(reg, url.strip()))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/git/CredMaster/credmaster.py", line 367, in create_api
    resource_id, proxy_url = fp.create_api(url)
                             ^^^^^^^^^^^^^^^^^^
  File "/home/kali/git/CredMaster/utils/fire.py", line 272, in create_api
    resource_id, proxy_url = self.create_deployment(response['id'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/git/CredMaster/utils/fire.py", line 350, in create_deployment
    response = self.client.create_deployment(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/git/CredMaster/venv/lib/python3.11/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/git/CredMaster/venv/lib/python3.11/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.TooManyRequestsException: An error occurred (TooManyRequestsException) when calling the CreateDeployment operation (reached max retries: 4): Too Many Requests
```

Possibly related to #48 ?

**Comment by knavesec** [comment]
Fixed in commit 0ed33a4, added max retries config option to the fireprox api
